package org.linphone.assistant;

public enum AssistantFragmentsEnum {
    WELCOME,
    CREATE_ACCOUNT,
    CREATE_ACCOUNT_ACTIVATION,
    CREATE_ACCOUNT_CODE_ACTIVATION,
    LINPHONE_LOGIN,
    COUNTRY_CHOOSER,
    LOGIN,
    REMOTE_PROVISIONING,
    ECHO_CANCELLER_CALIBRATION,
    DOWNLOAD_CODEC
}
